### ISSUE TITLE
Issue with inertias?

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/val_description#20]
I happened to fired up a demo program called ValkyrieSDFLoadingDemo in SCS.

And the inertial ellipses seem to be wrong for several joints - obviously the head:
https://www.dropbox.com/s/3l7u6tu3fl6vdpk/2015-10-val-inertias.m4v?dl=0

FYI @dljsjr

**Comment by jlack1987** [comment]
Hmm I am not sure, they look ok to me in Gazebo

**Comment by dljsjr** [comment]
@mauricefallon @jlack1987 We've been busy switching over to git the past few weeks. We've finished the migration now so we should be able to pay more attention to bug reports.

Given that, this will be at the top of the list.

**Comment by jlack1987** [comment]
Hey Maurice, it looks to me like the inertias are ok(at least for the head). There are some others I am going to do some looking into, but I don't see what your video shows for the head inertia. I took a screenshot, but it doesn't seem to allow attachments here. Lame. Make sure you are up to date and check again and let me know if it's still jacked up.

**Comment by jlack1987** [comment]
Ok so I have been investigating some of the inertias and have found a few issues. The weird shape you see in your video there with the head is something weird though that I can't even reproduce. The head mass I have in the URDF is wrong though, I am updating it to reflect the numbers from actually weighing the head link. I have also discovered some issues with how I am reflecting the mass parameters in the arms and am working on fixing those. Should be some time tomorrow(11/11) that I push a hotfix to master and it will contain a bunch of inertia fixes. Also we just pushed our alpha release stuff so master is where you should probably live from here on out. Let me know if you discover any more issues after I get the updates out.

**Comment by mauricefallon** [comment]
Ok, we haven't moved to using SCS with Git just yet. It will probably be a good while before I can check this with the latest val_description.
